# Generated by Django 5.0.3 on 2024-03-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_first_name_remove_account_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='aishe_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
