# Generated by Django 5.0.3 on 2024-03-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(default='default_photo.jpg', upload_to='passport_photos/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='verification_document',
            field=models.ImageField(default='default_verification_document.jpg', upload_to='verification_documents/'),
        ),
    ]
